# Generated by Django 6.0.2 on 2026-02-17 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=100)),
                ('UName', models.TextField(max_length=100)),
                ('Gender', models.BooleanField()),
                ('Profile_picture', models.URLField(blank=True, default='https://i.pinimg.com/1200x/83/bc/8b/83bc8b88cf6bc4b4e04d153a418cde62.jpg')),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Password', models.TextField()),
                ('Rating', models.FloatField(blank=True, default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_Number', models.SmallIntegerField(default=0)),
                ('Email', models.EmailField(max_length=254)),
                ('WhatsApp', models.SmallIntegerField(blank=True, default=0)),
                ('Facebook', models.URLField(blank=True)),
                ('Account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('County', models.TextField(max_length=100)),
                ('State', models.TextField(max_length=100)),
                ('Country', models.TextField(max_length=100)),
                ('Longitude', models.FloatField()),
                ('Latitude', models.FloatField()),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.account')),
            ],
        ),
    ]
