# Generated by Django 6.0.2 on 2026-02-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Verified',
            field=models.BooleanField(default=False),
        ),
    ]
