# Generated by Django 6.0.2 on 2026-02-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_account_managers_remove_account_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='Latitude',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='Longitude',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
