# Generated by Django 6.0.2 on 2026-03-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='pictureTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.ImageField(upload_to='pfp')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='Phone_Number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
