# Generated by Django 6.0.2 on 2026-03-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_picturetest_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturetest',
            name='image',
            field=models.ImageField(blank=True, upload_to='pfp'),
        ),
    ]
