# Generated by Django 6.0.2 on 2026-03-07 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_picturetest_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pictureTest',
        ),
    ]
