# Generated by Django 6.0.2 on 2026-03-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_delete_picturetest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='Account/PFP'),
        ),
    ]
