# Generated by Django 6.0.2 on 2026-03-20 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_delete_picturetest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
