# Generated by Django 6.0.2 on 2026-03-22 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_alter_account_profile_picture'),
        ('Accounts', '0008_alter_contact_account'),
    ]

    operations = [
    ]
