# Generated by Django 6.0.2 on 2026-03-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_merge_20260322_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='num_posts',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='num_reviews',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='type_of_user',
            field=models.CharField(choices=[('GUEST', 'Guest'), ('RENTER', 'Renter')], default='GUEST', max_length=20),
        ),
    ]
