# Generated by Django 6.0.2 on 2026-03-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_account_num_posts_account_num_reviews_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='num_reviews',
            new_name='num_review',
        ),
    ]
