# Generated by Django 6.0.2 on 2026-03-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_rename_num_reviews_account_num_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Phone_Number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
