# Generated by Django 6.0.2 on 2026-03-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_alter_account_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='verified',
        ),
        migrations.AlterField(
            model_name='account',
            name='type_of_user',
            field=models.CharField(choices=[('GUEST', 'Guest'), ('Host', 'Host')], default='GUEST', max_length=20),
        ),
    ]
