import type { Metadata } from "next";
import "@/styles/global.css"
import styles from "@/styles/layout_css/auth_layout.module.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <div className={styles.body_background}>
          {children}
        </div>
      </body>
    </html>
  );
}
