# Generated by Django 6.0.2 on 2026-03-24 11:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('type_of_user', models.CharField(choices=[('SELLER', 'Seller'), ('USER', 'ordinary user')], max_length=40)),
                ('num_review', models.IntegerField(default=0)),
                ('num_posts', models.IntegerField(default=0)),
                ('full_name', models.TextField(max_length=150)),
                ('gender', models.BooleanField(default=True)),
                ('date_of_birth', models.DateField(blank=True, default='2000-01-01', null=True)),
                ('profile_picture', models.URLField(blank=True, default='https://i.pinimg.com/1200x/83/bc/8b/83bc8b88cf6bc4b4e04d153a418cde62.jpg')),
                ('rating', models.FloatField(blank=True, default=0)),
                ('verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='account_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='account_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('County', models.TextField(blank=True, max_length=100)),
                ('State', models.TextField(blank=True, max_length=100)),
                ('Country', models.TextField(max_length=100)),
                ('Longitude', models.FloatField(blank=True, default=0)),
                ('Latitude', models.FloatField(blank=True, default=0)),
                ('Account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_Number', models.IntegerField(default=0, unique=True)),
                ('WhatsApp', models.SmallIntegerField(blank=True, default=0)),
                ('Facebook', models.URLField(blank=True)),
                ('Account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
