# Generated by Django 6.0.2 on 2026-03-09 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
        migrations.AddField(
            model_name='account',
            name='full_name',
            field=models.TextField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Phone_Number',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='Account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='County',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='Latitude',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='Longitude',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='State',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
