# Generated by Django 6.0.2 on 2026-03-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_account_managers_remove_account_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='num_review',
            field=models.IntegerField(default=0),
        ),
    ]
