# Generated by Django 6.0.2 on 2026-02-17 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Houses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('Title', models.TextField(max_length=100)),
                ('Description', models.TextField(max_length=1000)),
                ('House', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Houses.house')),
            ],
        ),
    ]
