# Generated by Django 6.0.2 on 2026-04-24 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='one_comment_per_user_per_post',
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(condition=models.Q(('comment', '__seller_rating__'), _negated=True), fields=('post', 'user'), name='one_nook_review_per_user_per_post'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(condition=models.Q(('comment', '__seller_rating__')), fields=('post', 'user'), name='one_seller_rating_per_user_per_post'),
        ),
    ]
