# Generated by Django 6.0.2 on 2026-03-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Likes',
        ),
        migrations.AddField(
            model_name='post',
            name='Rating',
            field=models.FloatField(default=5),
        ),
    ]
