# Generated by Django 6.0.2 on 2026-04-24 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_remove_comment_one_comment_per_user_per_post_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='one_nook_review_per_user_per_post',
        ),
        migrations.RemoveConstraint(
            model_name='comment',
            name='one_seller_rating_per_user_per_post',
        ),
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('post', 'Post'), ('seller', 'Seller')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'post'), _negated=True), fields=('post', 'user'), name='one_nook_review_per_user_per_post'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'seller')), fields=('post', 'user'), name='one_seller_rating_per_user_per_post'),
        ),
    ]
