# Generated by Django 6.0.2 on 2026-03-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_savedpost_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='post',
            name='Likes',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
