# Generated by Django 6.0.2 on 2026-04-24 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_remove_comment_one_nook_review_per_user_per_post_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='one_nook_review_per_user_per_post',
        ),
        migrations.RemoveConstraint(
            model_name='comment',
            name='one_seller_rating_per_user_per_post',
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'post'), _negated=True), fields=('post', 'user', 'type'), name='one_nook_review_per_user_per_post'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'seller')), fields=('post', 'user', 'type'), name='one_seller_rating_per_user_per_post'),
        ),
    ]
