# Generated by Django 6.0.2 on 2026-03-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_post_rating_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('archived', 'Archived'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('rented', 'Rented')], db_index=True, default='pending', max_length=10),
        ),
    ]
