# Generated by Django 6.0.2 on 2026-03-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
