# Generated by Django 6.0.2 on 2026-03-29 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_alter_post_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
