# Generated by Django 6.0.2 on 2026-03-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0008_post_current_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='current_tenant',
        ),
    ]
