# Generated by Django 6.0.2 on 2026-02-17 09:15

import Houses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvalabilityCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_at', models.DateTimeField(default=Houses.models.House.Creation_time)),
                ('end_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FeatureList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=75, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.IntegerField(default=0)),
                ('RoomNum', models.SmallIntegerField(default=1)),
                ('Surface', models.FloatField()),
                ('Description', models.TextField(max_length=1000)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('Types_of_Renters', models.CharField(choices=[('AL', 'All People'), ('FA', 'Families only'), ('NM', 'Doesnt Allow Males only'), ('NC', 'Doesnt Allow Couples'), ('NP', 'No Pets')], default='AL', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featues', models.ManyToManyField(blank=True, to='Houses.featurelist')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('County', models.TextField(max_length=100)),
                ('State', models.TextField(max_length=100)),
                ('Country', models.TextField(max_length=100)),
                ('Longitude', models.FloatField()),
                ('Latitude', models.FloatField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Houses.house')),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField(blank=True, default='https://images.template.net/465793/Blank-House-Clipart-edit-online.png')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Houses.house')),
            ],
        ),
    ]
