# Generated by Django 6.0.2 on 2026-02-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='featues',
            new_name='features',
        ),
    ]
