# Generated by Django 6.0.2 on 2026-03-31 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='featues',
            new_name='features',
        ),
        migrations.RemoveField(
            model_name='pictures',
            name='URL',
        ),
        migrations.AddField(
            model_name='features',
            name='house',
            field=models.ForeignKey(db_column='house_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='Houses.house'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='max_tenants',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='house',
            name='num_bathroom',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='house',
            name='num_bedroom',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='house',
            name='num_beds',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pictures',
            name='picture',
            field=models.ImageField(blank=True, default='', upload_to='Houses/pictures'),
        ),
        migrations.AlterField(
            model_name='location',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='Houses.house'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='Houses.house'),
        ),
        migrations.CreateModel(
            name='houseRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allows_animals', models.BooleanField(default=False)),
                ('allows_smoking', models.BooleanField(default=False)),
                ('allows_noise', models.BooleanField(default=False)),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='Houses.house')),
            ],
        ),
    ]
