# Generated by Django 6.0.2 on 2026-04-28 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0002_rename_featues_features_features_remove_pictures_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='house',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='Houses.house'),
        ),
    ]
