# Generated by Django 6.0.2 on 2026-03-14 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0002_rename_featues_features_features'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvalabilityCalendar',
            new_name='AvailablityCalendar',
        ),
        migrations.RenameField(
            model_name='features',
            old_name='features',
            new_name='Available_features',
        ),
        migrations.AddField(
            model_name='features',
            name='House',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Houses.house'),
            preserve_default=False,
        ),
    ]
