# Generated by Django 6.0.2 on 2026-03-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0003_rename_avalabilitycalendar_availablitycalendar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='Country',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='Latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='Longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='State',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
