# Generated by Django 6.0.2 on 2026-03-14 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0004_alter_location_country_alter_location_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='house',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Houses.house'),
        ),
    ]
