# Generated by Django 6.0.2 on 2026-03-14 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0005_alter_location_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='House',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='Houses.house'),
        ),
    ]
