# Generated by Django 6.0.2 on 2026-03-20 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0006_alter_features_house'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvailablityCalendar',
            new_name='AvalabilityCalendar',
        ),
        migrations.RenameField(
            model_name='features',
            old_name='Available_features',
            new_name='features',
        ),
        migrations.RenameField(
            model_name='features',
            old_name='House',
            new_name='house',
        ),
        migrations.AlterField(
            model_name='location',
            name='Country',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='Latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='Longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='State',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='Houses.house'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Houses.house'),
        ),
    ]
