# Generated by Django 6.0.2 on 2026-03-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0006_alter_features_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='URL',
        ),
        migrations.AddField(
            model_name='pictures',
            name='picture',
            field=models.ImageField(blank=True, upload_to='Houses/pictures'),
        ),
    ]
