# Generated by Django 6.0.2 on 2026-03-22 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0007_remove_pictures_url_pictures_picture'),
        ('Houses', '0007_rename_availablitycalendar_avalabilitycalendar_and_more'),
    ]

    operations = [
    ]
