# Generated by Django 6.0.2 on 2026-03-24 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0008_merge_20260322_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='picture',
        ),
        migrations.AddField(
            model_name='pictures',
            name='URL',
            field=models.URLField(blank=True, default='https://images.template.net/465793/Blank-House-Clipart-edit-online.png'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Houses.house'),
        ),
    ]
