# Generated by Django 6.0.2 on 2026-03-24 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0009_remove_pictures_picture_pictures_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='Houses.house'),
        ),
    ]
