# Generated by Django 6.0.2 on 2026-03-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0010_alter_pictures_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='num_bathroom',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='house',
            name='num_bedroom',
            field=models.SmallIntegerField(default=1),
        ),
    ]
