# Generated by Django 6.0.2 on 2026-03-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0011_house_num_bathroom_house_num_bedroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='URL',
        ),
        migrations.AddField(
            model_name='pictures',
            name='picture',
            field=models.ImageField(blank=True, upload_to='Houses/pictures'),
        ),
    ]
