# Generated by Django 6.0.2 on 2026-03-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0012_remove_pictures_url_pictures_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='picture',
            field=models.ImageField(blank=True, default='', upload_to='Houses/pictures'),
        ),
    ]
