# Generated by Django 6.0.2 on 2026-02-17 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=100)),
                ('UName', models.TextField(max_length=100)),
                ('Gender', models.BooleanField()),
                ('Profile_picture', models.URLField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Password', models.TextField()),
                ('Rating', models.FloatField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('County', models.TextField(max_length=100)),
                ('State', models.TextField(max_length=100)),
                ('Country', models.TextField(max_length=100)),
                ('Longitude', models.FloatField()),
                ('Latitude', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_Number', models.SmallIntegerField(default=0)),
                ('Email', models.EmailField(max_length=254)),
                ('WhatsApp', models.SmallIntegerField(blank=True, default=0)),
                ('Facebook', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Body', models.TextField(blank=True, max_length=1000)),
                ('Rating', models.SmallIntegerField(default=5)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posts.post')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
        ),
    ]
